### ISSUE TITLE
couleur des warnings dans le logger

### ISSUE THREAD

**Issue by rhomu** [phfaist/bibolamazi#3]
Les warnings s'affichent en jaune... impossible de les lire sur un terminal blanc! (meme en selectionant, chez moi)

Output:

Found Source: /home/muellrom/projects/thesis/bibliography/supplementary.bib
Filter: citearxiv: parsing & fetching relevant arxiv citations ...
Filter: citeinspirehep: parsing & fetching relevant InspireHEP citations ...
citeinspirehep: Fetching missing information from InspireHEP...
Starting new HTTPS connection (1): inspirehep.net
WARNING: Could not fetch reference for key `1411.0911v1':
        Your search did not match any records.  Please try again.
WARNING: Got either none or more than one bibtex entry when retreiving`inspire:1411.0911v1'!
Filter: only_used: filtering entries ...
Filter: arxiv
Filter: fixes
Filter: processing duplicate entries. Don't forget to insert `\input{duplicates.tex}' in your LaTeX file!
Filter: url
Filter: orderentries: Processing 34 entries
Filter: nameinitials
Updated output file`bibliography/references.bibolamazi.bib'.

**Comment by phfaist** [comment]
Yellow -> Magenta
c'est mieux? Aussi tu peux toujours virer les couleurs en définissant `BIBOLAMAZI_TTY_COLORS=no`.
-Philippe

**Comment by rhomu** [comment]
nickel
