### ISSUE TITLE
A tough nut for citeinspirehep

### ISSUE THREAD

**Issue by rhomu** [phfaist/bibolamazi#5]
Hoi,

J'essaie d'obtenir la citation d'un livre sur inspire. C'est ici:

http://inspirehep.net/search?ln=en&ln=en&p=j%3ACamb.Monogr.Part.Phys.Nucl.Phys.Cosmol.+8+%281996%29+1-435&of=hb&action_search=Search&sf=&so=d&rm=&rg=25&sc=0

La citation
\cite{j:Camb.Monogr.Part.Phys.Nucl.Phys.Cosmol.8(1996)1-435}
et correctement reconnue comme journal entry mais le fetch ne fonctionne pas pour deux raisons: 1) les espaces sont important 2) ca ne marche pas avec des virgules a la place des points.

Y'a moyen de faire marcher ca ou c'est la m..?

**Comment by phfaist** [comment]
J'arrive pas vraiment à comprendre: tout l'info qu'il faut, c'est "Camb.Monogr.Part.Phys.Nucl.Phys.Cosmol. 8 1", n'est-ce pas? Quelle est la requête inspire-hep correspondante? D'ailleurs, dans [la source du filter](https://github.com/phfaist/bibolamazi/blob/master/bibolamazi/filters/citeinspirehep.py#L121), tu changes les "." en "," (pourquoi?), donc ça ne te permet pas de justement d'insérer des virgules?

**Comment by rhomu** [comment]
bah essaie de comprendre (hint: les espaces)

Je ne me souviens pas d'avoir mis la ligne en question... Si elle ne pose pas de probleme avec le reste du prog, on peut simplement l'enlever.
